spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC
    password: 1000239
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true